services:
  openhands:
    image: ghcr.io/openhands/openhands:1.5.0
    container_name: openhands-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - AGENT_SERVER_IMAGE_REPOSITORY=${AGENT_SERVER_IMAGE_REPOSITORY:-ghcr.io/openhands/agent-server}
      - AGENT_SERVER_IMAGE_TAG=${AGENT_SERVER_IMAGE_TAG:-1.15.0-python}
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands:/.openhands
    stdin_open: true
    tty: true
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/_data:/home/node/n8n_data
    environment:
      - N8N_USER_MANAGEMENT_DISABLED=false
      - N8N_BASIC_AUTH_ACTIVE=true 
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - NODE_OPTIONS=--max-old-space-size=8096
      - N8N_METRICS=true
      - WEBHOOK_URL=${WEBHOOK_URL}
      - EXECUTIONS_TIMEOUT=-1
      - EXECUTIONS_TIMEOUT_MAX=36000
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    labels:
      - "dev.orbstack.domains=n8n.local"
    restart: always
    networks:
      - web

volumes:
  n8n_data:

networks:
  web: